use near_contract_standards::fungible_token::receiver::FungibleTokenReceiver;
use near_sdk::{json_types::U128, near, require, serde_json, AccountId, PromiseOrValue};
use sweat_jar_model::data::deposit::DepositTicket;

use crate::{migration::api::store_account_raw, Base64VecU8, Contract, ContractExt};

/// The `FtMessage` enum represents various commands for actions available via transferring tokens to an account
/// where this contract is deployed, using the payload in `ft_transfer_call`.
#[near(serializers=[json])]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
pub enum FtMessage {
    /// Represents a request to create a new jar for a corresponding product.
    Stake(StakeMessage),
    Migrate(AccountId, Base64VecU8),
}

/// The `StakeMessage` struct represents a request to create a new jar for a corresponding product.
#[near(serializers=[json])]
pub struct StakeMessage {
    /// Data of the `JarTicket` required for validating the request and specifying the product.
    ticket: DepositTicket,

    /// An optional ed25519 signature used to verify the authenticity of the request.
    signature: Option<Base64VecU8>,

    /// An optional account ID representing the intended owner of the created jar.
    receiver_id: Option<AccountId>,
}

#[near]
impl FungibleTokenReceiver for Contract {
    fn ft_on_transfer(&mut self, sender_id: AccountId, amount: U128, msg: String) -> PromiseOrValue<U128> {
        self.assert_from_ft_contract();

        let ft_message: FtMessage = serde_json::from_str(&msg).expect("Unable to deserialize msg");

        match ft_message {
            FtMessage::Stake(message) => {
                let receiver_id = message.receiver_id.unwrap_or(sender_id);
                self.deposit(receiver_id, message.ticket, amount.0, &message.signature);
            }
            FtMessage::Migrate(account_id, account_bytes) => {
                self.assert_migrate_from_previous_version(&sender_id);

                store_account_raw(account_id.clone(), account_bytes);
                require!(
                    self.get_account(&account_id).get_total_principal() == amount.0,
                    "Total principal mismatch"
                );
            }
        }

        PromiseOrValue::Value(0.into())
    }
}

#[cfg(test)]
mod tests {
    use std::panic::catch_unwind;

    use near_contract_standards::fungible_token::receiver::FungibleTokenReceiver;
    use near_sdk::{json_types::U128, serde_json::json, AccountId};
    use rstest::{fixture, rstest};
    use sweat_jar_model::{
        data::{
            deposit::{DepositMessage, Purpose},
            product::Product,
        },
        signer::test_utils::Base64String,
    };

    use crate::{
        common::testing::{
            accounts::{admin, alice},
            Context,
        },
        feature::product::model::test_utils::{product, protected_product, ProtectedProduct},
    };

    #[fixture]
    fn alice_migration_message() -> String {
        r#"{"data":["alice.near","AAgCAAAEAAAACQAAAHByb2R1Y3RfMcIBAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAAAAAAAAAAAAAAALPYaJKIpAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAHByb2R1Y3RfMjIAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAAAAAAAAAAAAAAA9ESCkWNFAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAHByb2R1Y3RfMwoAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAAAAAAAAAAAAAAAyE5nbcEbAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAHByb2R1Y3RfNAoAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAAAAAAAAAAAAAAAZKeztuANAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAA=="],"type":"migrate"}"#.to_string()
    }

    #[rstest]
    fn transfer_with_create_jar_message(admin: AccountId, alice: AccountId, product: Product) {
        let mut context = Context::new(admin).with_products(&[product.clone()]);

        let msg = json!({
            "type": "stake",
            "data": {
                "ticket": {
                    "product_id": product.id,
                    "valid_until": "0",
                }
            }
        });

        let ticket_amount = 1_000_000;
        context.switch_account_to_ft_contract_account();
        context
            .contract()
            .ft_on_transfer(alice.clone(), ticket_amount.into(), msg.to_string());

        let principal = context
            .contract()
            .get_account(&alice)
            .get_jar(&product.id)
            .total_principal();
        assert_eq!(ticket_amount, principal);
    }

    #[rstest]
    fn transfer_with_duplicate_create_jar_message(
        alice: AccountId,
        admin: AccountId,
        #[from(protected_product)] ProtectedProduct { product, signer }: ProtectedProduct,
    ) {
        let mut context = Context::new(admin).with_products(&[product.clone()]);

        let ticket_amount = 1_000_000u128;
        let ticket_valid_until = 100_000_000u64;
        let message = DepositMessage::new(
            Purpose::Deposit,
            &context.owner,
            &alice,
            &product.id,
            ticket_amount,
            ticket_valid_until,
            0,
        );
        dbg!(message.to_string());
        let signature: Base64String = signer.sign(message.as_str()).into();

        let msg = json!({
            "type": "stake",
            "data": {
                "ticket": {
                    "product_id": product.id,
                    "valid_until": ticket_valid_until.to_string(),
                },
                "signature": *signature,
            }
        });

        context.switch_account_to_ft_contract_account();
        context
            .contract()
            .ft_on_transfer(alice.clone(), ticket_amount.into(), msg.to_string());

        let principal = context
            .contract()
            .get_account(&alice)
            .get_jar(&product.id)
            .total_principal();
        assert_eq!(ticket_amount, principal);

        let result = catch_unwind(move || {
            context
                .contract()
                .ft_on_transfer(alice.clone(), U128(ticket_amount), msg.to_string())
        });
        assert!(result.is_err());
    }

    #[rstest]
    #[should_panic(expected = "Unable to deserialize msg")]
    fn transfer_with_unknown_message(alice: AccountId, admin: AccountId) {
        let mut context = Context::new(admin);

        context.switch_account_to_ft_contract_account();
        context
            .contract()
            .ft_on_transfer(alice, U128(300), "something".to_string());
    }

    #[rstest]
    #[should_panic(expected = "Can receive tokens only from token")]
    fn transfer_by_not_token_account(alice: AccountId, admin: AccountId) {
        let mut context = Context::new(admin);

        context.switch_account(&alice);
        context
            .contract()
            .ft_on_transfer(alice.clone(), U128(300), "something".to_string());
    }

    #[rstest]
    fn migrate_with_valid_message(alice: AccountId, admin: AccountId, alice_migration_message: String) {
        let mut context = Context::new(admin);

        context.switch_account_to_ft_contract_account();
        context.contract().ft_on_transfer(
            context.legacy_jar_contract_id.clone(),
            U128(1_630_000_000_000_000_000_000),
            alice_migration_message,
        );

        let contract = context.contract();
        let alice_account = contract.get_account(&alice);
        assert_eq!(4, alice_account.jars.len());
        assert_eq!(1_630_000_000_000_000_000_000, alice_account.get_total_principal());
    }
}
