[package]
name = "replay"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "replay"
path = "src/lib.rs"

[[bin]]
name = "replay"
path = "src/main.rs"

[dependencies]
sweat_jar = { path = "../contract", features = ["replay-engine"] }
sweat-jar-model = { workspace = true }
near-sdk = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled"] }
csv = "1.3"
clap = { version = "4.5", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
anyhow = { workspace = true }
ureq = { version = "2.10", features = ["json"] }
base64 = { workspace = true }

[dev-dependencies]
tempfile = "3"
