name: Build

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTIONS: true

jobs:

  build:
    strategy:
      fail-fast: true
      matrix:
        target: [
          { runner: ubuntu-latest, os: linux },
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: cargo test --all

      - name: Integration tests
        run: cargo run -p integration-tests

      - name: Build simple
        run: ./build.sh

      - name: Build in docker
        run: ./build-in-docker.sh
