name: Dispatch

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTIONS: true

jobs:

  dispatch:
    strategy:
      fail-fast: true
      matrix:
        target: [
          { runner: ubuntu-latest, os: linux },
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Build in docker
        run: ./build-in-docker.sh
