name: Measure

on:
  workflow_dispatch:
    inputs:
      number_of_jars:
        description: 'Number of maximum user jars'
        required: false
        default: '5'
      multiplier:
        description: 'Jars multiplier'
        required: false
        default: '10'

jobs:
  measure:
    runs-on: ubuntu-latest

    env:
      MEASURE_JARS_COUNT: ${{ github.event.inputs.number_of_jars }}
      MEASURE_JARS_MULTIPLIER: ${{ github.event.inputs.multiplier }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Measure gas
        run: make measure

      - name: Upload measure
        uses: actions/upload-artifact@v3
        with:
          name: measured
          path: measured.txt
