name: Mutation

on:
  workflow_dispatch:

jobs:
  measure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mutation test
        run: make mutation
